@FinancialAPI_URL = http://localhost:5000

GET {{FinancialAPI_URL}}/api/v1/users
Accept: application/json

###

GET {{FinancialAPI_URL}}/api/v1/users/cfb8058c-d08d-4cd9-a72c-9ea62109ee3d
Accept: application/json
###

POST {{FinancialAPI_URL}}/api/v1/users
Content-Type: application/json

{  
  "userName": "Marty McFly",
  "email": "marty_mcfly@example.com"
}

###

PUT  {{FinancialAPI_URL}}/api/v1/users/95e2e144-9665-4e6a-b947-dc40bd6882b9
Content-Type: application/json

{  
  "userId": "95e2e144-9665-4e6a-b947-dc40bd6882b9",
  "userName": "Bobby Tables",
  "email": "bt@gmail.com"
}

###

DELETE {{FinancialAPI_URL}}/api/v1/users/6ce72c55-5f12-462f-b8d3-abb5a2462629

###